# Generated by Django 5.1 on 2025-04-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_profile_first_name_and_more'),
        ('store', '0006_warehouse_category_parent_item_alert_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_purchase',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_categories',
            field=models.ManyToManyField(to='store.category'),
        ),
    ]
