# Generated by Django 5.1 on 2025-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_last_purchase_customer_preferred_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('CM', 'Commercial'), ('SM', 'Sales Manager'), ('AM', 'Account Manager')], default='CM', max_length=2, verbose_name='Rôle')),
                ('zone', models.CharField(max_length=50, verbose_name='Zone géographique')),
                ('sales_goal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Objectif mensuel (DH)')),
                ('achieved', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Réalisé (DH)')),
            ],
        ),
    ]
