# Generated by Django 5.1 on 2025-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_salesteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesteam',
            name='achieved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Objectif Réalisé (DH)'),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
    ]
