# Generated by Django 5.0.6 on 2025-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fabrication',
                'verbose_name_plural': 'Fabrications',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('component', models.CharField(max_length=100, verbose_name='Élément')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'verbose_name_plural': 'Nomenclatures',
            },
        ),
    ]
