# Generated by Django 5.0.6 on 2025-03-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_fabrication_nomenclature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabrication',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='product_name',
        ),
        migrations.AddField(
            model_name='fabrication',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fabrications', to='store.item', verbose_name='Produit fini'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='store.item', verbose_name='Produit fini'),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité fabriquée'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_nomenclatures', to='store.item', verbose_name='Matière première'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité nécessaire'),
        ),
    ]
