# Generated by Django 5.0.6 on 2025-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_fabrication_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_finished_product',
            field=models.BooleanField(default=False),
        ),
    ]
