# Generated by Django 5.2 on 2025-04-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_clientorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrication',
            name='origin_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrications', to='store.clientorder'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrications', to='store.item'),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
