# Generated by Django 5.2 on 2025-04-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_fabrication_origin_order_alter_clientorder_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrication',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En production'), ('ready', 'Prêt'), ('delivered', 'Livré'), ('canceled', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='origin_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.clientorder'),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
