# Generated by Django 5.2 on 2025-04-12 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_fabrication_is_confirmed_alter_clientorder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabrication',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='origin_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrications', to='store.clientorder'),
        ),
        migrations.AlterField(
            model_name='fabrication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrications', to='store.item'),
        ),
    ]
