# Generated by Django 5.1 on 2025-05-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('store', '0011_fabrication_confirmation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_number',
            field=models.CharField(max_length=13, verbose_name='numéro'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=300, verbose_name='client '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(editable=False, verbose_name='grand total '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_item',
            field=models.FloatField(verbose_name='Prix uniatire '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.FloatField(verbose_name='livraison '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(editable=False, verbose_name='prix total '),
        ),
    ]
