# Generated by Django 5.1 on 2025-05-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Addresse '),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description de la facture'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='bill',
            name='institution_name',
            field=models.CharField(max_length=30, verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_details',
            field=models.CharField(max_length=255, verbose_name='Details de paiement'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='numéro fournisseur'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
