# Generated by Django 5.1 on 2025-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReapprovisionnementFixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_livraison', models.IntegerField(verbose_name='Délai de livraison (en jours)')),
                ('consommation_annuelle', models.IntegerField(verbose_name='Consommation annuelle (en unités)')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix d’achat unitaire (en DH)')),
                ('taux_possession', models.FloatField(verbose_name='Taux de possession des stocks (en décimal, par exemple 0.08 pour 8%)')),
                ('cout_lancement', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût de lancement des commandes (en DH)')),
            ],
        ),
    ]
