# Generated by Django 5.1 on 2025-03-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_reapprovisionnementfixe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReapprovisionnementFixe',
        ),
    ]
