# Generated by Django 5.1 on 2025-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_reapprovisionnementfixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='policy_parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Paramètres de la politique'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='policy_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Politique utilisée'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
