# Generated by Django 5.1 on 2025-03-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_purchase_policy_parameters_purchase_policy_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
    ]
