# Generated by Django 5.1 on 2025-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_purchase_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='Taux_de_service',
            field=models.FloatField(default=95.0, verbose_name='Taux de service (en %)'),
        ),
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='case_a_cocher_de_stock_securite',
            field=models.BooleanField(default=False, verbose_name='Calculer le stock de sécurité'),
        ),
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='coefficient_securite_K',
            field=models.FloatField(default=0.0, verbose_name='Coefficient de sécurité K'),
        ),
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='ecart_type_delai',
            field=models.FloatField(default=0.0, verbose_name='Écart type du délai de livraison'),
        ),
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='ecart_type_demande',
            field=models.FloatField(default=0.0, verbose_name='Écart type de la demande'),
        ),
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='stock_securite',
            field=models.FloatField(default=0.0, verbose_name='Stock de sécurité (en unités)'),
        ),
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='type_variation',
            field=models.CharField(choices=[('1', 'Variation de la demande'), ('2', 'Variation du délai de livraison'), ('3', 'Variation des deux')], default='1', max_length=1),
        ),
    ]
