# Generated by Django 5.2 on 2025-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_reapprovisionnementfixe_taux_de_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
