# Generated by Django 5.2 on 2025-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_purchase_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reapprovisionnementfixe',
            name='taille_lot',
            field=models.PositiveIntegerField(default=1, verbose_name='Taille de lot'),
        ),
        migrations.AlterField(
            model_name='reapprovisionnementfixe',
            name='taux_possession',
            field=models.FloatField(verbose_name='Taux de possession des stocks (en décimal, par exemple 0.1 pour 10%)'),
        ),
    ]
