# Generated by Django 5.2 on 2025-05-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_fabrication_confirmation_date_and_more'),
        ('transactions', '0011_reapprovisionnementfixe_taille_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='store.clientorder'),
        ),
    ]
